// Generated by tools-build-programs.py -- Microtronic program library (.MIC text).
// The games by Björn Rathje are (c) Björn Rathje, https://github.com/rab-berlin, included with his permission.
"use strict";
const MICROTRONIC_PROGRAMS = [
{
"name": "17+4",
"title": "17 + 4 (Blackjack)",
"group": "From the Busch manuals",
"text": "# Black Jack 17+4\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 33) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nFE0\n14A\n1DB\n1DC\n1AD\n17E\n11F\nF6A\nFFF\nF02\nB6C\nC12\nF40\nB6C\nFFF\n\nF02\nE2C\n80D\nE15\nC1E\n9A0\nE18\nC1E\n902\nE1B\nC1E\n1A2\n1A3\nC5A\n0D0\n402\n\nD24\n992\nD24\nC26\n513\n562\n923\nE29\nC2C\n912\nE5A\nD60\n917\nD33\nE30\nC36\n\n966\nD33\nC36\n90F\nE53\nC0D\n84E\nE39\nC42\n9A4\nE3C\nC42\n903\nE3F\nC42\n1A6\n\n1A7\nC60\n0E4\n446\nD48\n996\nD48\nC4A\n566\n517\n927\nE4F\n90F\nE53\nC0D\n916\n\nE60\nD5A\nC4C\n837\nE57\nD60\nC5A\n826\nE60\nD60\n1DC\n10D\n10E\n16F\nF4C\nC64\n\n1DD\n1AE\n1BF\nF3D\n1FB\nFEB\nFFB\n104\nFE4\nF62\nFF0\nC00\nF05\n4FE\n9AD\nD71\n\nC73\n57D\nC6E\n9AE\nD76\nF07\n57E\nC73\n"
},
{
"name": "BATTLE",
"title": "Battle",
"group": "From the Busch manuals",
"text": "# Schlacht im Weltraum\n# Space / Battle Ships\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 6-7) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF02\nF08\nFE0\nB53\n0D0\n0E1\nB53\nB6D\nD06\n0D2\n0E3\nB53\nB68\nD0B\n0D4\n0E5\n\nB53\nB63\nD10\n0D6\n0E7\n10D\n10E\n10F\nF28\nFF9\nF28\nFF8\nF02\n51D\nFBE\n880\n\nE22\nC24\n891\nE38\n882\nE27\nC29\n893\nE3A\n884\nE2C\nC2E\n895\nE3C\n886\nE31\n\nC33\n897\nE3E\n1FC\nFEC\n10C\nFEC\nC18\n100\nC40\n102\nC40\n104\nC40\n106\n1FC\n\n1FA\nFEA\n10A\nFEA\n71C\nE47\nC40\n51F\n94F\nE4E\n1AA\n1AB\nF48\nC19\n10F\nF03\n\nF3D\nFF0\nC00\nF05\n90D\nE59\n95D\nD59\nC5B\n59D\nC54\n90E\nE60\n95E\nD60\nC62\n\n53E\nC5B\nF07\n8D4\nE66\nC68\n8E5\nE74\n8D2\nE6B\nC6D\n8E3\nE74\n8D0\nE70\nC72\n\n8E1\nE74\nF0A\nF07\nF09\nF07\n"
},
{
"name": "BIORYTHM",
"title": "Biorhythm (with Days)",
"group": "From the Busch manuals",
"text": "# Days Between Calculator\n# Part 1\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 34-35) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nF0E\nF08\nF6C\nFF2\n992\nD0E\n001\n0F0\n0EF\n0DE\n0CD\n02C\nC03\nF02\n017\n\n006\nB9E\n0C0\n0D1\nBAE\nF76\nF77\nF0D\nB9E\n110\n131\nF0B\nBBC\n90D\nD2D\n92C\n\nD2D\nB99\nBAE\nF0D\n140\nF0C\nBBC\nB99\nBAE\n10D\nC88\nBDF\nC43\nB9E\n0D1\n0C0\n\nF0D\n140\nF0B\n134\n125\nBA5\n010\n101\nBDF\nB99\nF0D\n140\nF0C\nBBC\nB99\n11D\n\nC88\n10D\nBDF\nB99\nF0D\nB9E\n150\n161\n132\nF0B\nBBC\nB9E\nF20\nFF1\nFF0\nF02\n\nBBC\nF0E\n90F\nD57\n1FF\nF7F\nC02\nF0F\nF0E\nBDF\nF58\nFF0\nC00\n\n@ 88\n\n10C\nF0D\nB9E\n112\nF0C\n114\nBA5\nF0D\n\nB9E\n130\nF0B\nF0D\n140\nF0C\n90D\nE2B\nC41\n0E0\n0F1\n062\n073\nCA2\n100\n101\n\n102\n103\n104\n105\nF07\n440\nDAA\n990\nDAA\nCAC\n560\n511\n451\nCA2\n710\nDB1\n\nF07\n760\n711\nDB5\nF07\n761\n712\nDB9\nF07\n762\n713\nF07\n408\nDC1\n998\nDC1\n\nCC3\n568\n519\n419\nDC8\n999\nDC8\nCCA\n569\n51A\n42A\nDCF\n99A\nDCF\nCD1\n56A\n\n51B\n43B\nDD6\n99B\nDD6\nCD8\n56B\n51C\n44C\nDDD\n99C\nDDD\nF07\n56C\nF07\n608\n\nDE2\nCE5\n768\n719\nDE8\n619\nDE9\nCEC\n619\n769\n71A\nDEF\n62A\nDF0\nCF3\n62A\n\n76A\n71B\nDF6\n63B\nDF7\nCFA\n63B\n76B\n71C\nDFD\n64C\nDFE\nF07\n64C\n76C\nF07\n\n# ---- addition, from address 51 ----\n# Biorythm Calculator\n# Part 3 - Load DAYS.MIC and WEEKDAY.MIC first\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 37) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 51\n\nF0E\n90F\nD57\n1FF\nF7F\nC02\nF0F\nF0E\nBDF\n136\n127\n11F\nC65\n186\n127\n\n12F\nC65\n136\n137\n13F\nF76\nF77\nB9E\n090\n0A1\n0B2\n0C3\nF0D\n060\n071\nF0C\n\nF0D\n012\n001\n080\nF0D\nB9E\n060\n071\nF0C\nF0D\n012\n001\n100\nF0D\nB9E\n060\n\n071\nF0C\nF10\nFF0\n92F\nE62\nD00\nC5E\n"
},
{
"name": "BLOCKADE",
"title": "Blockade",
"group": "From the Busch manuals",
"text": "# Blockade\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 7) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nFE0\n1A0\n151\n112\n113\nF2E\nFFF\nFFE\nB76\n91F\nE0F\n92F\nE11\nC00\n0E0\n\nC12\n0E1\nB5B\n664\n675\n845\nE18\nC1B\nB5B\nB60\nC06\nB5B\n516\n864\nD2B\nB5B\n\nB72\n905\nE28\n9F5\nE28\n9E5\nE28\nC2D\nB5B\nB6E\nC2D\nB5B\nB6E\n904\nE34\n9F4\n\nE34\n9E4\nE34\nC36\nB5B\nB72\n91F\nD3B\n042\n02E\nC3D\n053\n03E\n992\nE40\nC42\n\n943\nE43\nC06\n1FA\nFEA\n51B\nD48\nC43\nFE9\n1FB\n1FC\nF3A\nFF0\nC00\n1FA\nFEA\n\n10A\nFEA\n51B\nD55\nC4E\n1CA\n1CB\n1CC\nF3A\nFF0\nC00\n004\n015\n026\n037\nF07\n\n11F\n516\n864\nE67\n062\n02E\nF07\n726\n062\n02E\n924\nE6D\nF07\nC4E\n675\n654\n\n11F\nF07\n664\n645\n12F\nF07\n92F\nE80\n9AE\nD00\n8E2\nD00\nE00\n80E\nE00\nF07\n\n95E\nD00\n8E3\nD00\nE00\n81E\nE00\nF07\n"
},
{
"name": "CALC",
"title": "Calculator",
"group": "From the Busch manuals",
"text": "# Calculator\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 26-27) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\n917\nE05\nF0A\nC06\nF09\nF60\nFF6\nF02\n996\nD1D\n947\nD15\n187\n060\n101\n\n102\n103\n104\n105\nC03\n045\n034\n023\n012\n001\n060\n387\nC03\n9A6\nE33\n317\n\n90E\nE2A\n9CE\nE66\n9DE\nE99\n9EE\nE39\n9FE\nE3F\n06E\n07F\n008\n019\n02A\n03B\n\n04C\n05D\nC01\n347\n947\nE00\n147\n106\nC0E\n06E\nB49\nB53\nF0B\nD59\nC61\n06E\n\nB49\n104\n105\n10C\n10D\nB53\nF0C\nD59\nC61\n907\nE4F\n90F\nD51\n117\nC52\n90F\n\nD4D\n107\nF07\nF0F\n06E\nF0D\nF0F\n06E\nF07\n1E0\n1E1\n1E2\n1E3\n1E4\n1E5\n107\n\nC64\n9BE\nE64\nC2A\n10E\nC01\n06E\n907\nE6D\n90F\nEA2\n117\nC71\n90F\nE70\nCA2\n\n107\n480\nD76\n990\nD76\nC78\n560\n511\n491\nD7D\n991\nD7D\nC7F\n561\n512\n4A2\n\nD84\n992\nD84\nC86\n562\n513\n4B3\nD8B\n993\nD8B\nC8D\n563\n514\n4C4\nD92\n994\n\nD92\nC94\n564\n515\n4D5\nD59\n995\nD59\nC61\n06E\n907\nE9F\n90F\nEA2\nC6B\n90F\n\nEA4\nC6B\nF0F\n06E\n608\nDA7\nCAA\n768\n719\nDAD\n619\nDAE\nCB1\n619\n769\n71A\n\nDB4\n62A\nDB5\nCB8\n62A\n76A\n71B\nDBB\n63B\nDBC\nCBF\n63B\n76B\n71C\nDC2\n64C\n\nDC3\nCC6\n64C\n76C\n71D\nDCC\n65D\nDCD\nF0F\n107\n06E\nC61\n65D\n76D\n117\nF88\n\n768\nF89\n769\nF8A\n76A\nF8B\n76B\nF8C\n76C\nF8D\n76D\n110\n101\n102\n103\n104\n\n105\nC71\n"
},
{
"name": "CODE",
"title": "Code breaker",
"group": "From the Busch manuals",
"text": "# Code Breaker\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 9-10) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nF49\nFFC\nFFB\nFFA\nFF9\nF02\nF05\n4D9\n4EA\n4FB\n4DC\n579\n999\nD0C\n57A\n\n99A\nD0F\n8A9\nE0F\n57B\n99B\nD14\n8B9\nE14\n8BA\nE14\n57C\n99C\nD1B\n8C9\nE1B\n\n8CA\nE1B\n8CB\nE1B\n10D\n10E\n10F\nF61\nFF0\n9A0\nE33\nD31\n034\n023\n012\n001\n\nC27\nF49\nC60\nF02\n105\n106\n017\n098\nB65\n0A8\nB6A\n0B8\nB6A\n0C8\nB6A\n027\n\nB6A\n0B8\nB6A\n0A8\nB65\n098\nB6A\n037\nB6A\n0A8\nB6A\n0B8\nB65\n0C8\nB6A\n047\n\nB65\n0B8\nB6A\n0A8\nB6A\n098\nB6A\n51D\nFBE\nFBF\n946\nE5D\nC27\n1E0\n1E5\nF60\n\nFF0\nF03\nF3D\nFF0\nC00\n878\nE68\nC69\n516\nF07\n878\nE6D\nC6E\n515\nF07\n"
},
{
"name": "DAYS",
"title": "Days between dates",
"group": "From the Busch manuals",
"text": "# Days Between Calculator\n# Part 1\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 34-35) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nF0E\nF08\nF6C\nFF2\n992\nD0E\n001\n0F0\n0EF\n0DE\n0CD\n02C\nC03\nF02\n017\n\n006\nB9E\n0C0\n0D1\nBAE\nF76\nF77\nF0D\nB9E\n110\n131\nF0B\nBBC\n90D\nD2D\n92C\n\nD2D\nB99\nBAE\nF0D\n140\nF0C\nBBC\nB99\nBAE\n10D\nC88\nBDF\nC43\nB9E\n0D1\n0C0\n\nF0D\n140\nF0B\n134\n125\nBA5\n010\n101\nBDF\nB99\nF0D\n140\nF0C\nBBC\nB99\n11D\n\nC88\n10D\nBDF\nB99\nF0D\nB9E\n150\n161\n132\nF0B\nBBC\nB9E\nF20\nFF1\nFF0\nF02\n\nBBC\nF0E\n90F\nD57\n1FF\nF7F\nC02\nF0F\nF0E\nBDF\nF58\nFF0\nC00\n\n@ 88\n\n10C\nF0D\nB9E\n112\nF0C\n114\nBA5\nF0D\n\nB9E\n130\nF0B\nF0D\n140\nF0C\n90D\nE2B\nC41\n0E0\n0F1\n062\n073\nCA2\n100\n101\n\n102\n103\n104\n105\nF07\n440\nDAA\n990\nDAA\nCAC\n560\n511\n451\nCA2\n710\nDB1\n\nF07\n760\n711\nDB5\nF07\n761\n712\nDB9\nF07\n762\n713\nF07\n408\nDC1\n998\nDC1\n\nCC3\n568\n519\n419\nDC8\n999\nDC8\nCCA\n569\n51A\n42A\nDCF\n99A\nDCF\nCD1\n56A\n\n51B\n43B\nDD6\n99B\nDD6\nCD8\n56B\n51C\n44C\nDDD\n99C\nDDD\nF07\n56C\nF07\n608\n\nDE2\nCE5\n768\n719\nDE8\n619\nDE9\nCEC\n619\n769\n71A\nDEF\n62A\nDF0\nCF3\n62A\n\n76A\n71B\nDF6\n63B\nDF7\nCFA\n63B\n76B\n71C\nDFD\n64C\nDFE\nF07\n64C\n76C\nF07\n"
},
{
"name": "DIAGONALS",
"title": "Diagonals",
"group": "From the Busch manuals",
"text": "# Diagonals\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 55) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nF20\nFFF\n99F\nD08\n001\n0F0\nC02\nF02\nF70\nF71\n730\nD14\nF0B\nF0D\n120\n\nF0C\nF40\nFFF\nC00\n760\n711\nC0D\n"
},
{
"name": "HANOI",
"title": "Towers of Hanoi",
"group": "From the Busch manuals",
"text": "F08\nF0E\nF1F\nFFF\nF02\n1AE\n1CD\n1BC\nF0E\n11F\nC0D\nF60\nF00\nF0E\n91F\nD15\nF3D\nFF0\nF02\nF0E\nCB0\nF0E\nB70\nB70\nB70\nB70\nF0E\n0BF\n71F\n0AE\n09C\n08D\nF0E\nB50\n12F\nC0D\nB60\nB90\nB90\nB90\nB90\nF0E\nF3D\nFF0\nF02\nF0E\nB70\nB70\nB70\nB70\nF0E\n0BF\n71F\n08E\n09D\n0AC\nF0E\nB50\n13F\nC0D\nB60\nB90\nB90\nB90\nB90\nCB0\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n098\n0A9\n0BA\n0CB\n0DC\n0ED\n0FE\nF07\n000\n000\n000\n000\n000\n000\n000\n000\n0EF\n0DE\n0CD\n0BC\n0AB\n09A\n089\nF07\n000\n000\n000\n000\n000\n000\n000\n000\nF0D\nF0E\n010\n021\n032\n043\n054\n065\n076\n087\n098\n0A9\n0BA\n0CB\n0DC\n0ED\n0FE\nF0E\nF0D\nF07\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\nF0D\nF0E\n0EF\n0DE\n0CD\n0BC\n0AB\n09A\n089\n078\n067\n056\n045\n034\n023\n012\n001\nF0E\nF0D\nF07\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n91F\nE0B\n92F\nE24\n93F\nE3C\nF00\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n"
},
{
"name": "HUNDRED",
"title": "Hundred",
"group": "From the Busch manuals",
"text": "# 100 Wins\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 15) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF02\nF08\nFE0\nF05\n92E\nD07\nC0B\n52F\n6FD\nFCE\nC04\n11B\n1A2\n10F\nF03\nB8B\n\nF60\nB9E\nFF6\nE44\n996\nD11\nC1B\nB9E\nFF6\n996\nD17\n100\n101\n1A2\n060\nFF6\n\n996\nD25\n001\n060\nC1F\n911\nD2D\nE2B\n900\nE2D\nC33\n900\nE33\n100\n101\nB9E\n\nB9E\nB9E\nC18\nBAE\n993\nD37\nC39\n514\n563\n414\n994\nD3D\nC3F\n515\n564\nB90\n\n91A\nE7D\n92A\nE80\n05F\n04E\n03D\nF04\n8CE\nD4E\nE4C\nC51\n8DB\nD51\n5BB\nFBC\n\nC48\n0B8\n0C9\n6D8\nFC9\n6E9\n909\nD6B\n9A8\nD6B\n0BD\n0CE\n10F\nB8A\n998\nD68\n\nBA5\n1C2\nB90\n91A\nE80\n92A\nE7D\nC17\n111\n100\nC61\nF05\n97D\nBA8\nC71\n52D\n\nC6C\n4D3\n993\nD75\nC61\n563\n514\n994\nD7A\nC61\n564\n515\nC61\n1E6\n1E2\nC82\n\n1C6\n1C2\nF52\nB9E\nB9E\nB9E\nB9E\nB9E\nFF0\nC00\nF03\n0D3\n0E4\n0F5\nF07\nF01\n\n915\nE95\nD97\n10A\nF07\n904\nE99\n12A\nF07\n903\nE9C\nC97\n11A\nF07\n1F7\nFE7\n\n737\nEA3\nCA0\nFE7\nF07\n080\n101\nF07\nD6F\n90D\nE6F\n0D0\n101\nF07\n403\nD37\n\nF07\n"
},
{
"name": "LAWINE",
"title": "Lawine (Avalanche)",
"group": "From the Busch manuals",
"text": "# Zahlenlawine\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 5) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nFE0\nF02\nF05\n0D2\n0E3\n0F4\nF12\nB39\nF13\nB39\nF14\nB39\nF05\n0D5\n0E6\n\n0F7\nF15\nB39\nF16\nB39\nF17\nB39\nF05\n0D8\n0E9\n0FA\nF18\nB39\nF19\nB39\nF1A\n\nB39\nF05\n0DB\n0EC\nF1B\nB39\nF1C\nB39\nF05\nF1D\nB39\nF1E\nB39\nF1F\nB39\n1FF\n\n10E\n10D\nFEF\nFEE\n51D\nD37\nC32\nFF0\nC00\n511\nC98\nFF0\n802\nE3F\nC8E\n911\n\nE8D\nFF0\n803\nE45\nC8E\n921\nE8D\nFF0\n804\nE4B\nC8E\n931\nE8D\nFF0\n805\nE51\n\nC8E\n941\nE8D\nFF0\n806\nE57\nC8E\n951\nE8D\nFF0\n807\nE5D\nC8E\n961\nE8D\nFF0\n\n808\nE63\nC8E\n971\nE8D\nFF0\n809\nE69\nC8E\n981\nE8D\nFF0\n80A\nE6F\nC8E\n991\n\nE8D\nFF0\n80B\nE75\nC8E\n9A1\nE8D\nFF0\n80C\nE7B\nC8E\n9B1\nE8D\nFF0\n80D\nE81\n\nC8E\n9C1\nE8D\nFF0\n80E\nE87\nC8E\n9D1\nE8D\nFF0\n80F\nE8D\nC8E\nF07\n1F0\nFE0\n\n711\n01D\n10E\n10F\nF03\nF3D\nFF0\nC00\nF01\nF01\nF01\nF01\nF01\nF01\nF02\nC3B\n"
},
{
"name": "LUNAR",
"title": "Lunar Lander",
"group": "From the Busch manuals",
"text": "# Lunar Lander\n\n# Verified against the printed listing (Busch Microtronic Manual Part 1, p. 24) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF02\nF08\nFE0\n142\n1F3\n114\n125\n136\n187\n178\n1A1\n02D\n03E\n04F\nF03\nF5D\n\nFFB\nF02\n1B1\n10F\n05D\n06E\nF03\nF5D\nFFB\nF02\n1C1\n07D\n08E\nF03\nF5D\nFFB\n\n10D\n10E\nF2D\nFFB\n99B\nD29\n0DE\n0BD\nC22\nF02\n10F\nF04\n6D7\nFC8\nD69\n6E8\n\nD69\n75D\nFCE\nD5A\n4D2\nFB3\nFB4\n4E3\nFB4\n652\nFC3\nFC4\nD7B\n663\nFC4\nD7B\n\n6D5\nFC6\nD80\n6E6\nD80\n904\nD0A\n903\nD0A\n952\nD0A\n906\nD0A\n955\nD0A\n1E0\n\n1E1\n1E2\n1E3\n1E4\n1E5\n1F6\nFE6\nF60\nFF0\nC00\n6DF\n6F2\nFC3\nFC4\nD7B\n652\n\nFC3\nFC4\nD7B\n663\nFC4\nD7B\n4F5\nFB6\nC45\n1E0\n1A1\n1E2\n1A3\n1FF\n1FE\nFEF\n\n71E\nD73\nC70\nF40\nFEF\n10D\nFED\n71E\nD58\nF02\nC73\n1A0\n1A1\n1A2\n1A3\nC6D\n\n1F0\n1A1\n1F2\n1A3\nC6D\n"
},
{
"name": "MORSE",
"title": "Morse encoder",
"group": "From the Busch manuals",
"text": "# Morse Encoder\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 18-20) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF01\nF02\nF08\nFE0\nFF1\n9D1\nD29\n9A1\nEA2\n9B1\nEA9\n9C1\nEBE\nDB0\n155\n951\n\nD1F\n901\nE18\n615\nBD7\n711\nE18\nC14\n905\nE00\nBE3\n715\nC18\nF01\nF01\n751\n\n615\nBE3\n711\nE25\nC21\nBD7\n715\nE00\nC25\nFF2\n9F1\nE46\n902\nE60\n912\nE64\n\n922\nE68\n932\nE6C\n942\nE70\n952\nE74\n962\nE78\n972\nE7C\n982\nE80\n992\nE84\n\n9A2\nE88\n9B2\nE8C\n1B2\nC96\n902\nE62\n912\nE66\n922\nE6A\n932\nE6E\n942\nE72\n\n952\nE76\n962\nE7A\n972\nE7E\n982\nE82\n992\nE86\n9A2\nE8A\n9B2\nE8E\n9C2\nC96\n\n142\nC92\n182\nC96\n1A2\nC96\n182\nC94\n102\nC90\n122\nC96\n1C2\nC94\n102\nC96\n\n102\nC92\n172\nC96\n1A2\nC94\n142\nC96\n1C2\nC92\n182\nC92\n1E2\nC94\n162\nC96\n\n1D2\nC96\n142\nC94\n102\nC94\n182\nC90\n122\nC94\n112\nC96\n162\nC94\n192\nC96\n\n111\nC97\n121\nC97\n131\nC97\n141\nFA2\nD9D\nBD7\n711\nE9F\nC97\nBE3\nC9A\n906\n\nE00\nCC7\nBD7\nBE3\nBD7\nBE3\nBD7\nBE3\nC9F\nBE3\nBE3\nBD7\nBD7\nBE3\nBE3\nC9F\n\nBD7\nBD7\nBD7\n5FF\n5FF\nBE3\nBE3\nBE3\n5FF\n5FF\nBD7\nBD7\nBD7\nC00\n116\nF17\n\nFF7\nF27\nFF8\nEC6\nF60\nCC7\nF02\n1FF\n71F\nECB\nCC8\n4AD\n87D\nDD5\n0D2\n90E\n\nED3\n1E1\nC2A\n1F1\nC2A\n57D\nCCC\n1F4\nFE4\n5FF\n5FF\n104\nFE4\nFDE\nEE1\n53A\n\nF07\n5CA\nF07\n1F4\nFE4\n714\nEE8\nCE5\nFE4\nFDE\nEEC\nF8A\nF07\n"
},
{
"name": "NIMTWO",
"title": "Nim 2",
"group": "From the Busch manuals",
"text": "# Nim 2\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 12-13) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nFE0\nF10\nFF8\nF61\nFF3\nFF2\nFF1\nFF6\nFF5\n905\nE23\nC12\n105\nFF6\nF61\n\nFF5\nE10\n916\nE1E\n926\nE1A\n815\nD0E\n651\nC21\n825\nD0E\n652\nC21\n835\nD0E\n\n653\nB5C\nD4E\nF02\n01D\n02E\nB66\n8D3\nE35\nD42\n03D\n01E\nB66\n8D2\nE35\nD48\n\n02D\n03E\nB66\n8D1\nD4A\n901\nE39\n711\nC3E\n902\nE3D\n712\nC3E\n713\nB5C\nD59\n\nF31\nC0D\n918\nE35\n928\nE35\n0D3\nC3E\n0D2\nC3E\n918\nE35\n0D1\nC3E\n1F0\nFE1\n\n519\nE54\nFE0\nC4F\n1E5\n1E6\nF61\nFF0\nC00\n1F0\nFE0\nC54\n901\nD64\n902\nD64\n\n903\nD64\nF09\nF07\nF0A\nF07\n0EC\n2DC\nAED\nF8D\nACD\nF8D\nF07\n"
},
{
"name": "NUMGUESS",
"title": "Number guessing",
"group": "From the Busch manuals",
"text": "# Number Guessing\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 12-13) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nF02\nF05\n56D\n99D\nD03\n56E\n99E\nD06\n56F\n99F\nD09\n107\n108\n109\n19A\n\n19B\n19C\nF30\nFF6\n9A6\nE1E\n9B6\nE5E\n9C6\nE61\n012\n001\n060\nC12\n513\n9A3\n\nE22\nC2B\n563\nFB4\n9A4\nE27\nC2B\n564\nFB5\n9A5\nE5E\n829\nD5B\nE2F\nC36\n818\n\nD5B\nE33\nC36\n807\nD5B\nE5B\n82C\nD41\nE3A\nC5B\n81B\nD41\nE3E\nC5B\n80A\nD41\n\nC5B\n82F\nD58\nE45\nC54\n81E\nD58\nE49\nC54\n80D\nD58\nE4D\nC54\n1EC\n1E0\nF5C\n\nFF6\nF33\nFF6\nC00\n00A\n01B\n02C\nC5B\n007\n018\n029\nF67\nFF6\nC14\n1BC\n1B0\n\nC4F\nF33\nFF6\nC5B\n"
},
{
"name": "POWERS",
"title": "Powers",
"group": "From the Busch manuals",
"text": "# Powers\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 61) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nF30\nFF6\n996\nD09\n012\n001\n060\nC02\n02A\n019\n008\nF2D\nFFC\n99C\nD13\n\n0DE\n0CD\nC0D\n90E\nE16\nC18\n90D\nE27\nF02\nF04\n71D\nFCE\nE1E\nC20\n90D\nE29\n\nF0D\n0A2\n091\n080\nF0D\nF0B\nC1A\nF08\n110\nF60\nFFB\nC00\n"
},
{
"name": "PRIMES-ENUM",
"title": "Prime enumerator",
"group": "From the Busch manuals",
"text": "# PRIMES-ENUM  -  prime-number enumerator for the Busch Microtronic 2090\n#\n# Displays the primes 2, 3, 5, 7, 11, ... in decimal, one after another,\n# pausing after each, then HALTs after the last prime below 1000 (997).\n#\n# Just LOAD and RUN (no input needed) -- unlike the interactive PRIMES.MIC,\n# this one simply counts up and shows every prime it finds.\n#\n# Method: trial division by the built-in DIV, using DIV's remainder flag\n# and its quotient (for a sqrt(n) early-out).  See PRIMES-ENUM.asm for the\n# fully commented source.\n#\n# Delay length is tunable: the word at address 39 is  '3'  (the high nibble\n# 3 of instruction 13C = 'MOVI 3,C').  Raise it (up to F) for a longer pause\n# between numbers, lower it for a shorter one.\n#\n# Registers: R8/R9/RA = n (units/tens/hundreds), R6/R7 = trial divisor,\n#            RC/RD/RE = delay counters.  (c) source: CC BY 4.0.\n\n@ 00\n\nF08\nF74\nF75\n128\nB38\n138\n126\n107\n080\n091\n0A2\n103\nF70\nF71\nF72\nF73\n060\n071\n102\n103\nF0C\nE17\nC29\n902\nE1A\nC21\n817\nD28\nE1E\nC21\n860\nD21\nC28\n516\n9A6\nE25\nC08\n106\n517\nC08\nB38\n518\n9A8\nE2D\nC06\n108\n519\n9A9\nE32\nC06\n109\n51A\n9AA\nE37\nC06\nF00\nF38\n13C\n10D\n10E\n51E\nD3F\nC3C\n51D\nD42\nC3B\n71C\nD45\nC3A\nF07\n"
},
{
"name": "PRIMES",
"title": "Prime tester",
"group": "From the Busch manuals",
"text": "# Primes\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 58-59) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nFEF\nF50\nFFE\nFE5\n9BE\nD09\nE0C\nC00\n9CE\nD02\nC16\nFFF\n9AF\nEDA\nD18\n\n034\n023\n012\n001\n0F0\nC0C\nF02\nB77\nF02\nB90\nF0D\nF08\n168\nF0D\nF0F\nB77\n\nF0F\n904\nD2A\n903\nD33\n902\nD36\n901\nD3C\nC3F\n92A\nD2D\nC41\n909\nD30\nC41\n\n958\nD3F\nC41\n90A\nD3F\nC41\n929\nD39\nC41\n918\nD3F\nC41\n909\nD3F\nC41\n1FF\n\nC01\nF70\nF71\nF72\nF73\nF74\n680\nD49\nC4C\n760\n711\nD4F\n691\nD50\nC53\n691\n\n761\n712\nD56\n6A2\nD57\nC5D\n6A2\n762\n713\nD5B\nC5D\n763\n714\n900\nD65\n010\n\n021\n032\n043\n104\nC5D\n904\nD46\n903\nD46\n82A\nD1D\nE6D\nC46\n819\nD1D\nE71\n\nC46\n808\nD1D\nE75\nC46\nF0D\nC17\n510\n990\nD7B\nC90\n560\n511\n991\nD80\nC90\n\n561\n512\n992\nD85\nC90\n562\n513\n993\nD8A\nC90\n563\n514\n994\nD8F\nC90\n564\n\n910\nEA9\n920\nE9D\n930\nE9D\n970\nEA9\n990\nEA9\n950\nE9D\nC77\n904\nDA6\n903\n\nDA6\n902\nDA6\n901\nDA6\nCCF\n930\nEA9\nC77\nF70\nF71\nF72\nF73\nF74\n410\n101\n\n10F\nDD2\n990\nDD2\n420\n102\n11F\nDD2\n990\nDD2\n430\n103\n12F\nDD2\n990\nDD2\n\n440\n104\n13F\nDD2\n990\nDD2\n901\nDAE\n930\nED0\n960\nED0\n990\nED0\nF0D\nF07\n\nF0D\nC77\n560\n511\n92F\nDC4\nEBE\n90F\nDB8\nCB2\nF08\nC0C\n"
},
{
"name": "RACING",
"title": "Racing",
"group": "From the Busch manuals",
"text": "# Car Racing\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 27) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\n112\n124\nF40\nF05\n8D9\nE0D\n9FD\nE0D\n0D9\n515\nFB6\nC10\n71E\n6ED\nC05\n\nF06\n0A7\n0B8\n967\nD10\n527\nFE9\nFFC\n92C\nE2C\n99C\nE25\n95C\nE26\n91C\nE27\n\n9BC\nE29\n97C\nE2A\nC2B\nF94\nF94\nF94\nC2C\nFA4\nFA4\nFA4\n100\n101\n102\n103\n\n914\nE39\n924\nE3B\n944\nE3D\n984\nE3F\nC49\n113\nC40\n112\nC40\n111\nC40\n110\n\nF06\n87A\nD49\n88B\nE46\nC49\n098\n248\nE04\n10D\n10E\n10F\nF02\n51D\nD50\nC4C\n\nF40\n51E\nD54\nC50\n55F\nD57\nC4C\n10F\n05D\n06E\nF03\nF2D\nFFF\nC00\n"
},
{
"name": "RESISTOR",
"title": "Resistor decoder",
"group": "From the Busch manuals",
"text": "# Resistor Calculator\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 24) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF19\nF08\nFF0\n9B0\nD0D\n519\n949\nD00\n034\n023\n012\n001\nC02\n922\nD14\n902\n\nE1E\nB34\n712\nC0F\n952\nD1A\nB34\n1A3\n732\nC0F\nB34\n1B3\n762\nC0F\n911\nE2C\n\n921\nE2E\n9B1\nE30\n9A1\nE32\n12F\nF63\nFF0\nF2E\nFF0\nC00\n11E\nC27\n12E\nC27\n\n15E\nC27\n11F\nC27\n078\n067\n056\n045\n034\n993\nD3D\n103\nF07\n104\nF07\n"
},
{
"name": "SINUS",
"title": "Sine",
"group": "From the Busch manuals",
"text": "# Sinus Calculator\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 32) and corrected by Claude Code (Opus 5.5), October 2026.\n# Address 55: the manual prints 51D here but gives the mnemonic ADDI 1,B; 51B is the code for it.\n\n@ 00\n\nF08\nF20\nFF1\nFF0\nF02\nF0D\nF08\n140\n171\n112\nF0B\n00C\n01D\n02E\n03F\nB59\n\n0F1\n0E0\nF0D\n0F1\n0E0\nF0B\nF0D\n160\nF0C\nF0D\nB59\n0F1\n0E0\nF0B\n0C8\n0D9\n\n0EA\n0FB\n628\nD25\nC28\n768\n719\nD2B\n639\nD2B\nC2E\n769\n71A\nD31\n64A\nD32\n\nC34\n64A\n76A\n71B\n030\n041\nB5B\nF0D\n0E0\n0F1\nF0B\nF0D\n121\nF0C\nF0D\nB59\n\n0E0\n0F1\nF0B\n438\nD48\n998\nD48\nC4A\n568\n519\n449\nD4F\n999\nD4F\nC56\n569\n\n51A\n99A\nD54\nC56\n56A\n51B\nF48\nFF0\nC00\n100\n101\n102\n103\n104\n105\nF07\n"
},
{
"name": "SUPERDIV",
"title": "Super division",
"group": "From the Busch manuals",
"text": "# Super Division\n\n# Verified against the printed listing (Busch Microtronic Computer Games (2094), p. 57) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nF0D\nF0E\nF08\n1AF\nF2E\nFFE\n10F\nF0E\nB50\n00D\n01E\n02F\nF0D\nB50\n00A\n\n01B\n02C\nF0E\nF0C\nF30\nFF0\nF02\nF0D\n902\nD29\n901\nD29\n900\nD29\n94F\nE26\n\n0CD\n0BC\n0AB\n10A\n51F\nC1E\nF3B\nFFF\nC00\n023\n012\n001\n100\nF0D\nF0E\n0A0\n\n0B1\n0C2\nF0E\nF0C\n0CD\n0BC\n0AB\n00A\n51F\n94F\nE3C\nC17\n91E\nD43\n95A\nD41\n\nC26\n51B\nC26\n92E\nD4B\nF4A\nFFF\n9FF\nE00\n10F\nC16\nF4A\n518\n9F8\nE49\nC4C\n\nF10\nFF6\n996\nD63\n060\nFF6\n996\nD63\n001\n060\nF20\nFF6\n996\nD63\n012\n001\n\n060\nF30\nC5B\nF07\n"
},
{
"name": "TITATO",
"title": "Tic-Tac-Toe",
"group": "From the Busch manuals",
"text": "# Tic Tac Toe\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 5) and corrected by Claude Code (Opus 5.5), October 2026.\n# Address 23: the manual prints 02B here but gives the mnemonic CALL 2B; B2B is the code for it.\n\n@ 00\n\nF08\nF0D\nF08\nFE0\n198\nF28\nFF9\n51A\n94A\nE21\n09D\n51D\nB2B\n0C8\nFF9\n08D\n\n54D\nB2B\n89C\nE07\n0C8\n1CA\n1CB\nF48\n10F\nFEF\n516\nD1F\n1FF\nFEF\nC18\nFF0\n\nC00\n09D\n55D\nB2B\n0C8\n1EA\n1EB\n1FF\nFEF\nF48\nC1F\n0DC\n71D\n10E\nF03\n0D0\n\n0E1\nF0D\n180\nF0C\nF0D\n101\n180\nF0B\n60C\nF07\n"
},
{
"name": "WEEKDAY",
"title": "Weekday (with Days)",
"group": "From the Busch manuals",
"text": "# Days Between Calculator\n# Part 1\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 34-35) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 00\n\nF08\nF0E\nF08\nF6C\nFF2\n992\nD0E\n001\n0F0\n0EF\n0DE\n0CD\n02C\nC03\nF02\n017\n\n006\nB9E\n0C0\n0D1\nBAE\nF76\nF77\nF0D\nB9E\n110\n131\nF0B\nBBC\n90D\nD2D\n92C\n\nD2D\nB99\nBAE\nF0D\n140\nF0C\nBBC\nB99\nBAE\n10D\nC88\nBDF\nC43\nB9E\n0D1\n0C0\n\nF0D\n140\nF0B\n134\n125\nBA5\n010\n101\nBDF\nB99\nF0D\n140\nF0C\nBBC\nB99\n11D\n\nC88\n10D\nBDF\nB99\nF0D\nB9E\n150\n161\n132\nF0B\nBBC\nB9E\nF20\nFF1\nFF0\nF02\n\nBBC\nF0E\n90F\nD57\n1FF\nF7F\nC02\nF0F\nF0E\nBDF\nF58\nFF0\nC00\n\n@ 88\n\n10C\nF0D\nB9E\n112\nF0C\n114\nBA5\nF0D\n\nB9E\n130\nF0B\nF0D\n140\nF0C\n90D\nE2B\nC41\n0E0\n0F1\n062\n073\nCA2\n100\n101\n\n102\n103\n104\n105\nF07\n440\nDAA\n990\nDAA\nCAC\n560\n511\n451\nCA2\n710\nDB1\n\nF07\n760\n711\nDB5\nF07\n761\n712\nDB9\nF07\n762\n713\nF07\n408\nDC1\n998\nDC1\n\nCC3\n568\n519\n419\nDC8\n999\nDC8\nCCA\n569\n51A\n42A\nDCF\n99A\nDCF\nCD1\n56A\n\n51B\n43B\nDD6\n99B\nDD6\nCD8\n56B\n51C\n44C\nDDD\n99C\nDDD\nF07\n56C\nF07\n608\n\nDE2\nCE5\n768\n719\nDE8\n619\nDE9\nCEC\n619\n769\n71A\nDEF\n62A\nDF0\nCF3\n62A\n\n76A\n71B\nDF6\n63B\nDF7\nCFA\n63B\n76B\n71C\nDFD\n64C\nDFE\nF07\n64C\n76C\nF07\n\n# ---- addition, from address 51 ----\n# Calculate Weekday\n# Part 2 - Load DAYS.MIC first\n\n# Verified against the printed listing (Busch Microtronic Manual Part 2, p. 36) and corrected by Claude Code (Opus 5.5), October 2026.\n\n@ 51\n\nB9E\n090\n0A1\n0B2\n0C3\nF0D\n170\nF0C\n006\n017\n02E\nF0D\n001\n080\nF0D\n\nB9E\n170\nF0C\n061\n072\n0E3\nF0D\nB9E\n170\nF0B\nBDF\nF18\nFF0\nC00\n"
},
{
"name": "SEFFECT",
"title": "Sound: effect",
"group": "PicoRAM 2090 sound demos",
"text": "F10\n50D\n022\n000\n022\n011\n022\n033\n022\n044\n022\n055\n022\n066\n022\n077\n022\n088\n022\n099\n022\n0AA\n022\n0BB\n022\n0CC\nC01\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n"
},
{
"name": "SEQUENCER",
"title": "Sound: sequencer",
"group": "PicoRAM 2090 sound demos",
"text": "F60\nFF0\nFF1\nFF2\nFF3\nFF4\nFF5\nFF6\nFF7\nFF8\nFF9\nFFA\nFFB\nFFC\nFFD\nFFE\n50D\n011\n3F0\n011\n3F1\n011\n3F2\n011\n3F3\n011\n3F4\n011\n3F5\n011\n3F6\n011\n3F7\n011\n3F8\n011\n3F9\n011\n3FA\n011\n3FB\n011\n3FC\n011\n3FD\n011\n3FE\n011\n3FF\nC10\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n"
},
{
"name": "SOUND",
"title": "Sound: scale",
"group": "PicoRAM 2090 sound demos",
"text": "F10\n50D\n011\n3F0\n510\nC01\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n000\n"
},
{
"name": "KNIFFEL",
"title": "Kniffel (Yahtzee)",
"group": "Games by Björn Rathje",
"author": "Björn Rathje",
"url": "https://github.com/rab-berlin/Kniffel2090",
"setup": {},
"text": "# Kniffel2090 - (c) Björn Rathje\n# https://github.com/rab-berlin/Kniffel2090  (file: kniffel.mic)\n# Included unchanged, with the author's permission; all rights remain with him.\n\n#Machine Code\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1F8\nFE8\n1F9\n1FA\n11B\n\n1C0\nF70\n\nF0E\n\n136\n\nF60\n\n05D\nBC9\n0D5\n04D\nBC9\n0D4\n03D\nBC9\n0D3\n02D\nBC9\n0D2\n01D\nBC9\n0D1\n\n1BC\n\n1FF\nF03\n\n10A\n10B\n\n018\nBDB\n\n028\nBD0\nD25\n081\n092\n038\nBD0\nD2A\n082\n093\n048\nBD0\nD2F\n083\n094\n058\nBD0\nD34\n084\n095\n907\nD99\n7FC\nD1A\n\n716\n\n93B\nE3F\nD3E\n10B\nC42\n53B\n71B\n10A\nC4F\n\n72A\nD40\nE49\n91A\nE48\n58B\n18A\n54A\n821\nD4F\n854\nD4F\n51B\n\nFF7\n\n906\nE66\n\n917\nD58\nE56\nC09\n105\nC4F\n937\nD5F\nE5D\n104\nC4F\n103\nC4F\n957\nD66\nE64\n102\nC4F\n101\nC4F\n\n00C\n9B7\nD6C\n777\nD4F\nC7F\n070\nF70\n6C7\nD72\nE4F\nC73\n547\nF0E\n08C\n098\n0A9\n0BA\n0CB\n717\nE7C\nC74\nFE8\nF0E\nC4F\n\n927\nD82\nC84\n347\n547\nF0E\n287\nE7C\n678\nFE8\nF0E\n\n\n9C0\nD93\n747\nD90\nE91\nC1A\n517\n537\nC1A\n\n9D0\nD9E\n927\nD9B\n547\nC1A\nBF6\nCB1\n2A7\nEB1\nCB0\n\n9E0\nDB0\n2B7\nEB1\n11E\n19D\n927\nDA8\nEAE\nCB0\n947\nEAC\n5AD\nFBE\n5AD\nFBE\n55D\nFBE\nBEE\n\nF08\nF0D\nF70\nF0D\n\nF0E\nA86\nA96\nAA6\nAB6\nEBC\nC07\n\nF3D\nF0D\n511\nFB2\n742\nDC6\n12E\n13D\nBEF\nF0D\n\nF0F\nF03\nCC8\n\n\n\n\n90D\nDCF\nF05\n95D\nDCB\n51D\nF07\n\n898\nDE5\n9FC\nED5\nCDB\n689\n719\nDE7\nEEC\n10B\n10F\n907\nEE0\n887\nEE0\nCE2\n48D\nFBE\n089\nF09\nF07\nF0A\nF07\n51F\n8FA\nDDB\n0FA\nCDB\n51B\nCDA\n\nF0D\n4D5\nFB6\nFB7\n4E6\nFB7\nF0D\nF07\n\nF0D\n4D1\nFB2\n4E2\nCEF\n"
},
{
"name": "MENSCH",
"title": "Mensch ärgere dich nicht (Ludo)",
"group": "Games by Björn Rathje",
"author": "Björn Rathje",
"url": "https://github.com/rab-berlin/Mensch2090",
"setup": {
"patch": [
3,
3
]
},
"text": "# Mensch2090 - (c) Björn Rathje\n# https://github.com/rab-berlin/Mensch2090  (file: program/mensch.mic)\n# Included unchanged, with the author's permission; all rights remain with him.\n\n110\nF0D\n110\n\nFEC\n\nF1D\n\nF05\n95D\nD05\n51D\n\n10E\n\nBB0\nBC3\nD16\nE16\n96D\nE11\nC20\n118\nBE2\nE20\n110\nC61\nBBF\nD20\nBE2\nE20\n\n11E\nBC8\nBD1\nBD7\nF0D\nE4C\n\nBB3\nBC3\nD26\nE25\nC32\n11C\nBBF\nD32\nBE9\nE32\n52E\n91C\nE4C\nBC8\nBD1\nBD7\nF0D\nE4C\n\nBB6\nBC3\nD38\nE37\nC44\n11C\nBBF\nD44\nBF0\nE44\n54E\n91C\nE4C\nBC8\nBD1\nBD7\nF0D\nE4C\n\nBB9\nBC3\nD49\nE49\nC4C\nBBF\nD4C\n\n58E\n\n\n\n90E\nEA4\nFDC\nE59\nFFF\n92F\nD54\nC56\n34F\n54F\n2EF\nE50\n0FE\n\nFAE\nD64\nFAE\nD69\nFAE\nD6E\n4D0\nFB1\nBB0\n11E\nC72\n4D6\nFB7\nBB9\n14E\nC72\n4D4\nFB5\nBB6\n13E\nC72\n4D2\nFB3\nBB3\n12E\n\nBCB\nD89\n\nBC8\nBD1\nF0D\nBF0\nE80\nBE9\nE82\nBE2\nE84\nBDB\nE86\nC88\n057\n046\n035\n024\n013\n002\n101\n100\nF0D\n\nBB3\nBBC\nBB0\nBF2\nD92\n0B1\n0A0\n093\n082\nBB6\nBBC\nBB3\nBF2\nD9B\n0B3\n0A2\n095\n084\nBB9\nBBC\nBB6\nBF2\nDA4\n0B5\n0A4\n097\n086\n\nF2D\nFFF\n\nBB0\nBCB\nDAF\n\nFDC\n96D\nE03\nF0D\n58C\nC03\n\nF00\n\n\n\n\n\n019\n008\nF07\n039\n028\nF07\n059\n048\nF07\n079\n068\nF07\n\n09B\n08A\nF07\n\n4D8\nFB9\n1CF\nCCC\n\n10C\n909\nDC7\n918\n\n\n\nF07\n\n548\nFB9\n519\n18F\n929\nECF\nF07\n8F8\nF07\n\nDD3\nF07\n788\nFC9\n729\nF07\n\nF0D\nFDC\nEDB\nF07\n01B\n00A\n89B\nEE0\nCE2\n88A\nEF6\n03B\n02A\n89B\nEE7\nCE9\n88A\nEF6\n05B\n04A\n89B\nEEE\nCF0\n88A\nEF6\n07B\n06A\n89B\nEF5\nCF6\n88A\nF07\n"
},
{
"name": "MONARCH",
"title": "Monarch — Rotomat slot machine",
"group": "Games by Björn Rathje",
"author": "Björn Rathje",
"url": "https://github.com/rab-berlin/Monarch2090",
"setup": {
"piezo": 0,
"G": 0,
"H": 1
},
"text": "# Monarch2090 - (c) Björn Rathje\n# https://github.com/rab-berlin/Monarch2090  (file: program/2090pur/monarch.mic)\n# Included unchanged, with the author's permission; all rights remain with him.\n\nF08\n\nFFE\nF04\n\nF4C\n1E5\nBE6\n9FF\nE00\nBEF\n\nFEA\nE0F\nF0E\nF2D\nBEF\nF0E\n\n0D5\n0E6\n0F7\n\nF50\n\nBF6\n1F4\n1D3\n98D\nD2C\n1E4\n193\n97D\nD2C\n1B4\n96D\nD2C\n184\n95D\nD2C\n143\n94D\nD2C\n1B4\n93D\nD2C\n1A4\n91D\nD2C\n1C4\n\nBF6\n588\nD31\n929\nE14\n1F0\n1D1\n98D\nD46\n1E0\n191\n97D\nD46\n180\n96D\nD46\n1B1\n95D\nD46\n141\n93D\nD46\n1A0\n91D\nD46\n1C0\n\nBF6\n1F2\n98D\nD57\n1C2\n97D\nD57\n142\n95D\nD57\n182\n93D\nD57\n1A2\n91D\nD57\n1D2\n\n05D\n06E\n07F\n\nBEF\n109\n10B\nBFC\n\n840\nE63\n841\nE63\nC64\n048\n\n830\nE69\n831\nE69\nC6A\n039\n\n9E2\nD75\n\n828\nE6F\nC70\n08B\n829\nE73\nC7C\n09B\nC7C\n\n12B\n88B\nD79\n08B\n89B\nD7C\n09B\n\n99B\nE80\nD81\nC90\n1A5\n\n9AB\nE84\nC85\n1C5\n\n9BB\nE88\nC89\n1E5\n\n9CB\nE8D\nD9A\nC91\n105\n116\nC91\n\n0B5\n\n90A\nE9C\n\n90B\nD9A\n942\nE9A\n9C2\nD9A\nCA3\n\n145\n116\n\n906\nDA0\n905\nEA3\n\n111\nFE1\nFEA\n\nF0F\nF3C\nBEF\nF02\nF0F\n\nBE8\nBFC\n\n90A\nEC6\n\nF0E\n\n1F5\nBE6\nBFC\n\n7F2\nDC5\n\n90E\nDC5\n\n99D\nDBF\nEBD\n125\n\n90D\nDC5\n\n116\n145\nCC5\n\n1A5\nCC5\n\n9ED\nDC3\nEC4\nCC5\n\n136\n125\n\nF0E\n\n906\nDD2\n9A5\nED2\n\n9EB\nDD0\nECE\nCD2\n155\nCD1\n1A5\n12A\n\nFEA\nEE2\n\nF0F\nF2D\nBEF\nF0F\nF02\n\nF0E\nBE8\n90E\nDE1\n90D\nDE1\n10A\nF7A\nF0E\n\n102\n101\n\n103\nC03\n\n\n\n1F6\n1F7\n45D\nFBE\nFBF\n46E\nFBF\n47F\nF07\n\nF03\n108\n7F8\n10C\nDF1\nF04\nF07\n\nFD9\nEF6\nF05\n99D\nDF8\nF07\n\n105\n106\n107\nF07\n"
}
];
