#!/usr/bin/env python3
"""Bundle .MIC programs into js/programs.js (run from the emulator directory).

    python3 tools-build-programs.py ~/git/Busch-2090/software ~/git/picoram2090/software/1.1

The games in programs/rathje/ are always included.
"""
import sys, os, json, glob
TITLES = {
 '17+4':'17 + 4 (Blackjack)','BATTLE':'Battle','BIORYTHM':'Biorhythm (with Days)','BLOCKADE':'Blockade','CALC':'Calculator',
 'CODE':'Code breaker','DAYS':'Days between dates','DIAGONALS':'Diagonals','HAL9000':'HAL 9000','HANOI':'Towers of Hanoi',
 'HELLO':'Hello','HUNDRED':'Hundred','LAWINE':'Lawine (Avalanche)','LUNAR':'Lunar Lander','MORSE':'Morse encoder',
 'NIMTWO':'Nim 2','NUMGUESS':'Number guessing','POWERS':'Powers','PRIMES-ENUM':'Prime enumerator (to 997, then halts)','PRIMES-LOOP':'Prime enumerator, endless (press a key 0-F for the pause)','PRIMES':'Prime tester',
 'RACING':'Racing','RESISTOR':'Resistor decoder','SINUS':'Sine','SUPERDIV':'Super division','TITATO':'Tic-Tac-Toe','WEEKDAY':'Weekday (with Days)',
}
# Wiring the manuals ask for.  piezo: output the buzzer goes to (0 = output 1, the manuals' standard wiring, Part 1 p. 7);
# clock: input the 1 Hz clock is patched to (3 = input 4).
WIRING = {n: {'piezo': 0} for n in ('LAWINE', 'BLOCKADE', 'HUNDRED', '17+4', 'PRIMES', 'BATTLE', 'NIMTWO', 'LUNAR')}
WIRING['RACING'] = {'clock': 3}
WIRING['MORSE'] = {'piezo': 0, 'clock': 3}
SKIP = {'HAL9000', 'HELLO'}          # need the speech synthesizer
SOUND = {'SOUND': 'Sound: scale', 'SEFFECT': 'Sound: effect', 'SEQUENCER': 'Sound: sequencer'}
# Games by Björn Rathje (programs/rathje/*.MIC): title, repository, and the wiring each one needs.
# setup: piezo = output the buzzer is wired to, G/H = input of the red keys, patch = [output, input] cable (all 0-based)
RATHJE = {
 'MONARCH': ('Monarch — Rotomat slot machine', 'Monarch2090', {'piezo': 0, 'G': 0, 'H': 1}),
 'KNIFFEL': ('Kniffel (Yahtzee)', 'Kniffel2090', {}),
 'MENSCH':  ('Mensch ärgere dich nicht (Ludo)', 'Mensch2090', {'patch': [3, 3]}),
}
out = []
for d in sys.argv[1:]:
    for f in sorted(glob.glob(os.path.join(os.path.expanduser(d), '*.MIC'))):
        name = os.path.splitext(os.path.basename(f))[0]
        if name in SKIP or any(o['name'] == name for o in out): continue
        text = open(f, errors='replace').read()
        if name in ('WEEKDAY', 'BIORYTHM'):     # these are additions to DAYS: load them on top of it
            text = open(os.path.join(os.path.dirname(f), 'DAYS.MIC')).read() + '\n# ---- addition, from address 51 ----\n' + text
        if name in TITLES: out.append({'name': name, 'title': TITLES[name], 'group': 'From the Busch manuals', 'text': text, **({'setup': WIRING[name]} if name in WIRING else {})})
        elif name in SOUND: out.append({'name': name, 'title': SOUND[name], 'group': 'PicoRAM 2090 sound demos', 'text': text})
VIB = [('ORGAN-LONG', 'Mini organ, long tones'), ('ORGAN-SHORT', 'Mini organ, short tones'), ('COMPOSER', 'The composing computer'),
       ('MUSICBOX', 'Music box: three melodies'), ('LUNAR-SOUND', 'Moon Landing with sound effects')]
for name, title in VIB:
    out.append({'name': name, 'title': title, 'group': 'With the tone circuit (manual Part 2)', 'setup': {'vib': True}, 'text': open(f'programs/sound/{name}.MIC').read()})
for f in sorted(glob.glob('programs/rathje/*.MIC')):
    name = os.path.splitext(os.path.basename(f))[0]
    title, repo, setup = RATHJE[name]
    out.append({'name': name, 'title': title, 'group': 'Games by Björn Rathje', 'author': 'Björn Rathje',
                'url': 'https://github.com/rab-berlin/' + repo, 'setup': setup, 'text': open(f).read()})
with open('js/programs.js', 'w') as fh:
    fh.write('// Generated by tools-build-programs.py -- Microtronic program library (.MIC text).\n'
             '// The games by Björn Rathje are (c) Björn Rathje, https://github.com/rab-berlin, included with his permission.\n'
             '"use strict";\nconst MICROTRONIC_PROGRAMS = ')
    json.dump(out, fh, indent=0, ensure_ascii=False)
    fh.write(';\n')
print(len(out), 'programs')
