#!/usr/bin/env python3
"""Bundle .MIC programs into js/programs.js (run from the emulator directory).

    python3 tools-build-programs.py ~/git/Busch-2090/software ~/git/picoram2090/software/1.1
"""
import sys, os, json, glob
TITLES = {
 '17+4':'17 + 4 (Blackjack)','BATTLE':'Battle','BIORYTHM':'Biorhythm','BLOCKADE':'Blockade','CALC':'Calculator',
 'CODE':'Code breaker','DAYS':'Days between dates','DIAGONALS':'Diagonals','HAL9000':'HAL 9000','HANOI':'Towers of Hanoi',
 'HELLO':'Hello','HUNDRED':'Hundred','LAWINE':'Lawine (Avalanche)','LUNAR':'Lunar Lander','MORSE':'Morse encoder',
 'NIMTWO':'Nim 2','NUMGUESS':'Number guessing','POWERS':'Powers','PRIMES-ENUM':'Prime enumerator','PRIMES':'Prime tester',
 'RACING':'Racing','RESISTOR':'Resistor decoder','SINUS':'Sine','SUPERDIV':'Super division','TITATO':'Tic-Tac-Toe','WEEKDAY':'Weekday',
}
SKIP = {'HAL9000', 'HELLO'}          # need the speech synthesizer
SOUND = {'SOUND': 'Sound: scale (PicoRAM)', 'SEFFECT': 'Sound: effect (PicoRAM)', 'SEQUENCER': 'Sound: sequencer (PicoRAM)'}
out = []
for d in sys.argv[1:]:
    for f in sorted(glob.glob(os.path.join(os.path.expanduser(d), '*.MIC'))):
        name = os.path.splitext(os.path.basename(f))[0]
        if name in SKIP or (name not in TITLES and name not in SOUND) or any(o['name'] == name for o in out): continue
        out.append({'name': name, 'title': TITLES.get(name) or SOUND[name], 'text': open(f, errors='replace').read()})
with open('js/programs.js', 'w') as fh:
    fh.write('// Generated by tools-build-programs.py -- Microtronic program library (.MIC text).\n"use strict";\nconst MICROTRONIC_PROGRAMS = ')
    json.dump(out, fh, indent=0)
    fh.write(';\n')
print(len(out), 'programs')
